dev_yodaIT_Dose_url=http://uat.yodalifeline.in/yoda_uat_8.0/Design/Default.aspx

excel.filePath=src/test/resources/TestData/MrYodaStaging.xlsx
excel.sheetName=Diagnostics
excel.sheetName_dna=DNADecoder
excel.rowNum=1
base.url=https://dev-api-yodadiagnostics.yodaprojects.com

mobile.number=9003730394
nonMemberMobile.number=9666666665
country.code=+91
static.otp=123456
username_ITDose=Thirumala
password_ITDose=qwerty1234
